/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Это файл для Figma Make песочницы
// На продакшене используйте .env файл с VITE_POCKETBASE_URL
export const projectId = ""
export const publicAnonKey = ""